### ISSUE TITLE
causes visual glitch with company-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [purcell/page-break-lines#12] opened 2016-11-29 08:08 UTC
<img width="418" alt="screen shot 2016-11-29 at 13 35 00" src="https://cloud.githubusercontent.com/assets/5226809/20701408/da105a02-b638-11e6-81fe-9fbb45503676.png">

`company-mode` popup will glitch like shown above when there is a page break line below it's popup area.

**Comment by purcell** [comment] 2016-12-04 07:42
Which Emacs version do you have? I can't reproduce this with the latest Emacs, Company and page-break-lines-mode, so it's likely due to a bug that has been fixed in either company or Emacs. In any case, there wouldn't be anything that this code could do to avoid this issue.

**Comment by CSRaghunandan** [comment] 2016-12-04 07:43
I'm using 25.1-1 emacs on macOS

**Comment by purcell** [comment] 2016-12-05 05:16
Same version here. Does it only happen when completing on that _exact_ line relative to the page break?

**Comment by CSRaghunandan** [comment] 2016-12-05 05:31
I'm not sure how to reproduce this bug really. It glitches on some modes while on other modes it works fine. Here's another screenshot, this time in `rust-mode`

<img width="381" alt="screen shot 2016-12-05 at 10 53 28" src="https://cloud.githubusercontent.com/assets/5226809/20874582/49e4425e-bad9-11e6-85a8-2319ec71d8f7.png">

I'm not sure there is something in my config that's causing it to glitch. Can you reproduce this bug at all?

**Comment by purcell** [comment] 2016-12-05 05:35
> I'm not sure there is something in my config that's causing it to glitch. Can you reproduce this bug at all?

Nope. I'd suggest figuring out a reproduction case starting from `emacs -Q`, then manually loading `page-break-lines-mode` and `company` etc. There's probably some other conflicting package which uses display tables. IIRC I've seen something like this before, perhaps in an old Company issue. /cc @dgutov.

**Comment by CSRaghunandan** [comment] 2016-12-05 05:59
A found a way to reproduce in `emacs -Q`:

* `(package-initialize)`
* open any `.el` file or typing even in scratch buffer will do
* enable `page-break-lines-mode` and `company-mode`
* insert a page break character
* open a new line before the page break line char
* type `(require 'ini)`  and wait for company dialog box to open

I am able to reproduce the glitch with this method.

**Comment by dgutov** [comment] 2016-12-05 10:21
@purcell Isn't this https://github.com/company-mode/company-mode/issues/416?

It never started working in my setup.

**Comment by purcell** [comment] 2016-12-09 08:54
Hah, I knew I'd seen it before somewhere! I'll close this issue in favour of the other one.

**Closed by purcell** 2016-12-09 08:54 UTC
