### ISSUE TITLE
shorter rule when truncate-lines is nil

### ISSUE THREAD

**Issue by shynur** [purcell/page-break-lines#38] opened 2023-06-27 13:05 UTC
When `truncate-lines` is nil, the rule is wrapped:

![image](https://github.com/purcell/page-break-lines/assets/98227472/1637b13f-a2bb-47e1-b957-8374cf047f0a)

Can we use a shorter one, say `(1- ...)`?

**Comment by purcell** [comment] 2023-06-27 15:17
Duplicate of https://github.com/purcell/page-break-lines/issues/37, see discussion there

**Closed** 2023-06-27 15:20 UTC
